### ISSUE TITLE
Having loadouts of different genders inside the same profile breaks armor/gear/etc...

### ISSUE THREAD

**Issue by alt4** [HALOMAXX/BLREdit#12]
## Description

Mixing genders in a profile apparently breaks anything that isn't weapon-related (gear, armor, tac...): changing one piece of armor affects loadouts of different sex.

All-male or female profiles work as expected.

## Steps to reproduce

* Create a new BLREdit folder
* Change helmet on Loadout 1
* Swap to Loadout 2
* Change helmet on Loadout 2
* Tick `Female`
* Swap back to Loadout 1, helmet should be changed there too
* Close BLREdit, look inside the profile JSON: both loadouts should have the same helmet

## Additional context

Version 0.6.0

Previous release (0.5.3) apparently doesn't have this issue.

**Comment by HALOMAXX** [comment]
should be fixed with commit dfc13990817142f8189d5d974f4b79e4b4e54dfa
fix will be in the next update

**Comment by HALOMAXX** [comment]
Update has been released
