### ISSUE TITLE
Cannot close MapModeSelect window

### ISSUE THREAD

**Issue by MajiKau** [HALOMAXX/BLREdit#15]
Cannot close MapModeSelect window by clicking on the X. Only way to close the window is to click on one of the Start buttons.
Steps to reproduce:
1. Run BLREdit
2. Navigate to Launcher -> Client List
3. Click on Bot Match
4. Try to close the window

Using newest version of master ([66b89b4](https://github.com/HALOMAXX/BLREdit/commit/66b89b40d975ade864fece9ec5885b06bbc53fbd))
![image](https://user-images.githubusercontent.com/25136341/194535316-6338bcc4-a4f9-4d0a-bd5b-f8c8c2ea8a58.png)

**Comment by HALOMAXX** [comment]
Changed behaviour of the MapModeSelectWindow to cancel the launch of the bot match when closing the window 153925a1c1b1560509f1be080c2f9d8f9b8aa907
