### ISSUE TITLE
[Suggestion] Word Wrap Scrolling for Tactical Gear

### ISSUE THREAD

**Issue by KaleThyself** [HALOMAXX/BLREdit#16]
In the BLREdit GUI, when choosing a tactical gear for any loadout, the scrolling is horizontal instead of vertical due to there being 4 items per row on a typical 1920x1080 fullscreen resolution. Would it be possible to implement a QoL word wrap for the selections to exclusively vertical scroll with 2 items per row instead of having to scroll horizontally with 4 items per row? Perhaps resolution-friendly GUI scaling would be beneficial as well to prevent awkward horizontal scroll bars.

**Comment by HALOMAXX** [comment]
i changed the tactical gear to just use two columns in the next Update v0.7.5 it's not yet fully dynamic will close this if it's fully dynamic.

**Comment by HALOMAXX** [comment]
Item List Scaling is now fully dynamic with update v0.7.5
