### ISSUE TITLE
[BUG] Turret Crashes Local Server

### ISSUE THREAD

**Issue by KaleThyself** [HALOMAXX/BLREdit#18]
When using a turret from the depot in a local server against bots, the server immediately disconnects the player and crashes. 

### BLREdit Version:
v.0.7.3

### Logs:
[BLRevive-1666983601.log](https://github.com/HALOMAXX/BLREdit/files/9891139/BLRevive-1666983601.log)

**Comment by HALOMAXX** [comment]
not sure if it's because of BLREdit but changed the botmatch start behaviour (now also starts the client) to minimise this error.

**Comment by HALOMAXX** [comment]
can't reproduce this problem on my end and haven't gotten more complaints about this problem will close this for now.
