### ISSUE TITLE
[ BUG ] Problems with the Loadout

### ISSUE THREAD

**Issue by C3ldri0N** [HALOMAXX/BLREdit#21]
i cant use the Loadout on the servers ( i have all and follow the instructions of Hedraun ) but i cant play with my Loadout, i prefer write the loadout to one bot and get my loadout after death that no get my equipment

**Comment by HALOMAXX** [comment]
could you get me the log(log.txt) Next to BLREdit.exe so i can check what is going wrong

**Comment by C3ldri0N** [comment]
nothing, now work
( reset the PC with all instaled )

**Comment by HALOMAXX** [comment]
ok so you won't be able to get the log's. if you don't get it running let me know.
