### ISSUE TITLE
Settings Manager not showing saved settings at first launch

### ISSUE THREAD

**Issue by Hedraun** [HALOMAXX/BLREdit#25]
Settings saved in the past are appearing as default when starting the game initially
This can be resolved by getting into a local server then closing and then going into the actual game. 
Proxy log that ends in 75 is the log where it failed. 86 is the log where I went back ingame after some time and it was fine and settings were all there and applied.

[log.txt](https://github.com/HALOMAXX/BLREdit/files/10203388/log.txt)
[BLRevive-1670795875.log](https://github.com/HALOMAXX/BLREdit/files/10203396/BLRevive-1670795875.log)
[BLRevive-1670796386.log](https://github.com/HALOMAXX/BLREdit/files/10203397/BLRevive-1670796386.log)

**Comment by HALOMAXX** [comment]
I have added in-game settings management to BLREdit based on PlayerName which should also Copy the settings to a new client and maybe even make sure it gets properly loaded. could you test if this still happens with version v0.11.0.

**Comment by HALOMAXX** [comment]
should not happen anymore
