### ISSUE TITLE
adjustments for the new build

### ISSUE THREAD

**Issue by IvoOrdway** [HALOMAXX/BLREdit#4]
finally getting around to testing out the latest build here are the issues I have found so far:

bugs:
- the burstfire smg should be like the tsmg with no stock or barrel
- the lp and hp I found a issue where if you select a barrel mod and a stock you can remove the barrel mod and the stock stays
- gear items lower in the list give the wrong number in return like the tactical ice axe and most the effects grenades. (probable cause: gear item# 29-32 are unused in game (burning man, infected fingernails, etc.) and is throwing off the count)

features upcoming releases I think could probably consider implementing:
- armor stats
- gear slots limited by armor type

All in all its a pretty decent job keep up the good work.

**Comment by HALOMAXX** [comment]
so far i got gear items fixed, burst fire smg now doesn't have stock and barrel mod, fixed bug with the light pistol and heavy pistol. Armor stats are currently not possible as we don't have the stats available will take some more time. just a tip please separate your future issues so i can better complete them.

**Comment by HALOMAXX** [comment]
added Armor stats for new version and also gear slot limiting according to Armor gear slots. will be available in the new version v0.3.0
