### ISSUE TITLE
Trojan virus error

### ISSUE THREAD

**Issue by ftk789** [HALOMAXX/BLREdit#53]
![image](https://user-images.githubusercontent.com/57598907/229073329-2bb09f62-acae-44ee-9dd1-b4ffb7138d0d.png)

**Comment by HALOMAXX** [comment]
Sry can't really change that flag, we need to binary patch the BLR-client to make it work which might get flagged as virus.

**Comment by ftk789** [comment]
Ahh that makes sense, Thank you for clarifying and thank you for an awesome project.
