### ISSUE TITLE
BLREdit will not open after downloading dependencies

### ISSUE THREAD

**Issue by ProblematicReality** [HALOMAXX/BLREdit#55]
[05.11.2023(021632).log](https://github.com/HALOMAXX/BLREdit/files/11450469/05.11.2023.021632.log)

Failing after Validating Client List with a null reference exception. Initially it booted to tell me I needed Visual C++ Redistributables, but after validating my install (As I already had them) it consistently does the above even after a full clean out and reinstall.

**Comment by ProblematicReality** [comment]
It appears it works intermittently if I click it enough but I am unable to see and modules or patches, so there's only partial functionality

**Comment by HALOMAXX** [comment]
I made some changes. Could you check if the problem persists. And if it does please also send me a new log file

**Comment by HALOMAXX** [comment]
the problem has been resolved with confirmation over discord. thanks for helping me find this bug and fixing it.
