### ISSUE TITLE
Forbid special chars in player name

### ISSUE THREAD

**Issue by alt4** [HALOMAXX/BLREdit#66]
Hello,

Since "non-standard" characters in usernames have been known to cause issues with servers, I will probably look into a way to deal with those server-side, but I don't think I can handle it in a way that doesn't involve dropping the connection/kicking the player out, which would give them little to no feedback as to why.

Would it be possible to disallow (or at least heavily warn against) special characters in player names directly in BLREdit to (hopefully) alleviate the problem somewhat? Ideally only characters valid in a windows file path (a-z lower and upper case, 0-9 and dashes/underscores) would be allowed.

**Comment by HALOMAXX** [comment]
this will be in the next release
